language: ruby
os: linux
dist: xenial
jdk: openjdk11

git:
  quiet: true

env:
  global:
    - BALLERINA_INSTALLER_DEB=ballerina-linux-installer-x64-${BALLERINA_VERSION}.deb
    - BALLERINA_INSTALLER_DEB_URL=http://dist-dev.ballerina.io/downloads/${BALLERINA_VERSION}/${BALLERINA_INSTALLER_DEB}

services:
  - docker

jobs:
  include:
  - stage: Test
    name: "Crypto"
    before_install:
      - wget ${BALLERINA_INSTALLER_DEB_URL}
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
    script:
      - ballerina -v
      - cd test-suite
      - ./scripts/crypto/setup.sh || travis_terminate 1
      - ballerina build -c crypto || travis_terminate 1
  - name: "Encoding"
    before_install:
      - wget ${BALLERINA_INSTALLER_DEB_URL}
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
    script:
      - ballerina -v
      - cd test-suite
      - ./scripts/encoding/setup.sh || travis_terminate 1
      - ballerina build -c encoding || travis_terminate 1
  - name: "Basic Auth"
    before_install:
      - wget ${BALLERINA_INSTALLER_DEB_URL}
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
    script:
      - ballerina -v
      - cd test-suite
      - ballerina build -c basicauth --b7a.config.file=basicauth/users.toml || travis_terminate 1
      - ./scripts/auth.basic/ballerina.sh || travis_terminate 1
      - ./scripts/auth.basic/test.sh || travis_terminate 1
  - name: "JWT Auth"
    before_install:
      - wget ${BALLERINA_INSTALLER_DEB_URL}
      - docker pull ldclakmal/wso2is-sts:latest
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
      - sudo apt-get install jq
    script:
      - ballerina -v
      - cd test-suite
      - ballerina build -c jwtauth || travis_terminate 1
      - ./scripts/auth.jwt/docker.sh || travis_terminate 1
      - ./scripts/auth.jwt/ballerina.sh || travis_terminate 1
      - ./scripts/auth.jwt/test.sh || travis_terminate 1
  - name: "OAuth2"
    before_install:
      - wget ${BALLERINA_INSTALLER_DEB_URL}
      - docker pull ldclakmal/wso2is-sts:latest
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
      - sudo apt-get install jq
    script:
      - ballerina -v
      - cd test-suite
      - ./scripts/auth.oauth2/docker.sh || travis_terminate 1
      - ballerina build -c oauth2 || travis_terminate 1
      - ./scripts/auth.oauth2/ballerina.sh || travis_terminate 1
      - ./scripts/auth.oauth2/test.sh || travis_terminate 1
  - name: "LDAP Auth"
    before_install:
      - wget ${BALLERINA_INSTALLER_DEB_URL}
      - docker pull osixia/openldap:1.3.0
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
    script:
      - ballerina -v
      - cd test-suite
      - ./scripts/auth.ldap/docker.sh || travis_terminate 1
      - ballerina build -c ldapauth || travis_terminate 1
      - ./scripts/auth.ldap/ballerina.sh || travis_terminate 1
      - ./scripts/auth.ldap/test.sh || travis_terminate 1
