language: ruby
os: linux
dist: xenial

git:
    quiet: true

services:
    - docker

before_install:
    - wget https://product-dist.ballerina.io/downloads/1.2.0/ballerina-linux-installer-x64-1.2.0.deb
    - docker pull ldclakmal/wso2is-sts:latest
install:
    - sudo dpkg -i ballerina-linux-installer-x64-1.2.0.deb
    - sudo apt-get install -f
    - sudo apt-get install jq
script:
    - ballerina --version
    - ballerina build -c auth.oauth2 || travis_terminate 1
after_script:
    - ./scripts/auth.oauth2/run-docker.sh || travis_terminate 1
    - ./scripts/auth.oauth2/run-bal.sh || travis_terminate 1
    - ./scripts/auth.oauth2/run-tests.sh || travis_terminate 1
