language: ruby
os: linux
dist: xenial

git:
  quiet: true

services:
  - docker

jobs:
  include:
  - stage: Secured Services
    name: "Basic Auth"
    before_install:
      - wget https://product-dist.ballerina.io/downloads/${BALLERINA_VERSION}/${BALLERINA_INSTALLER_DEB}
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
    script:
      - ballerina -v
      - ballerina build -c auth.basic || travis_terminate 1
      - ./scripts/auth.basic/ballerina.sh || travis_terminate 1
      - ./scripts/auth.basic/test.sh || travis_terminate 1
  - name: "JWT Auth"
    before_install:
      - wget https://product-dist.ballerina.io/downloads/${BALLERINA_VERSION}/${BALLERINA_INSTALLER_DEB}
      - docker pull ldclakmal/wso2is-sts:latest
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
      - sudo apt-get install jq
    script:
      - ballerina -v
      - ballerina build -c auth.jwt || travis_terminate 1
      - ./scripts/auth.jwt/docker.sh || travis_terminate 1
      - ./scripts/auth.jwt/ballerina.sh || travis_terminate 1
      - ./scripts/auth.jwt/test.sh || travis_terminate 1
  - name: "OAuth2"
    before_install:
      - wget https://product-dist.ballerina.io/downloads/${BALLERINA_VERSION}/${BALLERINA_INSTALLER_DEB}
      - docker pull ldclakmal/wso2is-sts:latest
    install:
      - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
      - sudo apt-get install -f
      - sudo apt-get install jq
    script:
      - ballerina -v
      - ballerina build -c auth.oauth2 || travis_terminate 1
      - ./scripts/auth.oauth2/docker.sh || travis_terminate 1
      - ./scripts/auth.oauth2/ballerina.sh || travis_terminate 1
      - ./scripts/auth.oauth2/test.sh || travis_terminate 1
  - name: "LDAP Auth"
    before_install:
        - wget https://product-dist.ballerina.io/downloads/${BALLERINA_VERSION}/${BALLERINA_INSTALLER_DEB}
        - docker pull osixia/openldap:1.3.0
    install:
        - sudo dpkg -i ${BALLERINA_INSTALLER_DEB}
        - sudo apt-get install -f
    script:
        - ballerina -v
        - ballerina build -c auth.ldap || travis_terminate 1
        - ./scripts/auth.ldap/docker.sh || travis_terminate 1
        - ./scripts/auth.ldap/ballerina.sh || travis_terminate 1
        - ./scripts/auth.ldap/test.sh || travis_terminate 1
