language: ruby
os: linux
dist: xenial

git:
  quiet: true

services:
  - docker

jobs:
  include:
  - stage: Secured Services
    name: "JWT"
    before_install:
      - wget https://product-dist.ballerina.io/downloads/1.2.0/ballerina-linux-installer-x64-1.2.0.deb
      - docker pull ldclakmal/wso2is-sts:latest
    install:
      - sudo dpkg -i ballerina-linux-installer-x64-1.2.0.deb
      - sudo apt-get install -f
      - sudo apt-get install jq
    script:
      - ballerina --version
      - ballerina build -c auth.jwt || travis_terminate 1
      - ./scripts/common/docker.sh || travis_terminate 1
      - ./scripts/auth.jwt/ballerina.sh || travis_terminate 1
      - ./scripts/auth.jwt/test.sh || travis_terminate 1
  - name: "OAuth2"
    before_install:
      - wget https://product-dist.ballerina.io/downloads/1.2.0/ballerina-linux-installer-x64-1.2.0.deb
      - docker pull ldclakmal/wso2is-sts:latest
    install:
      - sudo dpkg -i ballerina-linux-installer-x64-1.2.0.deb
      - sudo apt-get install -f
      - sudo apt-get install jq
    script:
      - ballerina --version
      - ballerina build -c auth.oauth2 || travis_terminate 1
      - ./scripts/common/docker.sh || travis_terminate 1
      - ./scripts/auth.oauth2/ballerina.sh || travis_terminate 1
      - ./scripts/auth.oauth2/test.sh || travis_terminate 1
