title: Ballerina Security
author: Chanaka Lakmal - @ldclakmal
social:
    name: Chanaka Lakmal - @ldclakmal
    links:
        - https://linkedin.com/in/ldclakmal
        - http://github.com/ldclakmal
        - https://medium.com/@ldclakmal
        - https://twitter.com/ldclakmal92
        - https://www.facebook.com/ldclakmal92
        - https://stackoverflow.com/users/4314651/ldclakmal?tab=profile
        - https://www.flickr.com/people/ldclakmal
