version: "3"
services:
  nats-tls:
    image: nats:latest
    container_name: nats-server
    command: "-c /server.conf"
    volumes:
      - "./server.conf:/server.conf"
      - "./cert/server.crt:/cert/server.crt"
      - "./key/server.key:/key/server.key"
      - "./cert/ca.crt:/cert/ca.crt"
    ports:
      - "4222:4222"
      - "8222:8222"
