[[ballerina.auth.users]]
username="alice"
password="alice@123"
scopes=["add-order","view-order"]

[[ballerina.auth.users]]
username="bob"
password="bob@123"
scopes=["view-order"]

[[ballerina.auth.users]]
username="eve"
password="eve@123"
