[book]
authors = ["Chanaka Lakmal"]
language = "en"
multilingual = false
src = "src"
title = "Ballerina Security"

[output.html]
theme = "theme"
default-theme = "light"
git-repository-url = "https://github.com/ldclakmal/ballerina-security"
edit-url-template = "https://github.com/ldclakmal/ballerina-security/edit/master/docs/src/{path}"

[output.html.fold]
enable = true