[[ballerina.auth.users]]
username="alice"
password="alice123"
scopes=["add-order","view-order"]

[[ballerina.auth.users]]
username="bob"
password="bob123"
scopes=["view-order"]

[[ballerina.auth.users]]
username="eve"
password="eve123"
