name: Validate Ballerina Version

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: 'GitHub Artifact ID of the Ballerina ZIP produced during Ballerina daily build'
        required: false

jobs:
  validate:
    name: Ballerina Version
    runs-on: ubuntu-latest
    env:
      BALLERINA_DEB_URL: ${{ secrets.BALLERINA_DEB_URL }}
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download & Install Ballerina
        run: ./_resources/scripts/install.sh ${{ github.event.inputs.artifact_id }}
      - name: Test
        run: bal -v
