name: BBE

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.jpg'
  workflow_dispatch:

jobs:
  crypto:
    name: Cryptographic Operations
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/crypto.sh
  jwt:
    name: JWT Issue & Validate
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/jwt.sh
  url:
    name: URL Encode & Decode
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/url.sh
  http-ssl-tls:
    name: HTTP - SSL/TLS
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_ssl_tls.sh
  http-mtls:
    name: HTTP - mTLS
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_mtls.sh
  http-basic-auth-file-store:
    name: HTTP - Basic Auth (File)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_basic_auth_file_store.sh
  http-basic-auth-ldap-store:
    name: HTTP - Basic Auth (LDAP)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_basic_auth_ldap_store.sh
  http-jwt-auth:
    name: HTTP - JWT Auth
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_jwt_auth.sh
  http-oauth-bearer-token:
    name: HTTP - OAuth2 (Bearer Token)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_oauth2_bearer_token.sh
  http-oauth-client-credentials-grant:
    name: HTTP - OAuth2 (Client Credentials Grant)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_oauth2_client_credentials_grant.sh
  http-oauth-password-grant:
    name: HTTP - OAuth2 (Password Grant)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_oauth2_password_grant.sh
  http-oauth-refresh-token-grant:
    name: HTTP - OAuth2 (Refresh Token Grant)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/http_oauth2_refresh_token_grant.sh
  graphql-ssl-tls:
    name: GraphQL - SSL/TLS
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/graphql_ssl_tls.sh
  graphql-mtls:
    name: GraphQL - mTLS
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/graphql_mtls.sh
  graphql-basic-auth-file-store:
    name: GraphQL - Basic Auth (File)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/graphql_basic_auth_file_store.sh
  graphql-basic-auth-ldap-store:
    name: GraphQL - Basic Auth (LDAP)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/graphql_basic_auth_ldap_store.sh
  graphql-jwt-auth:
    name: GraphQL - JWT Auth
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/graphql_jwt_auth.sh
  graphql-oauth-bearer-token:
    name: GraphQL - OAuth2 (Bearer Token)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/bbe
        run: |
          scripts/graphql_oauth2_bearer_token.sh
