name: BBE

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.jpg'
  workflow_dispatch:

jobs:
  security-crypto:
    name: Cryptographic Operations
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        # run: wget https://dist.ballerina.io/downloads/swan-lake-alpha3/ballerina-linux-installer-x64-swan-lake-alpha3.deb
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/security/crypto.sh
  security-url:
    name: URL Encode & Decode
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/security/url.sh
  security-jwt:
    name: JWT Issue & Validate
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/security/jwt.sh
  access-control-basic-auth-file-store:
    name: HTTP - Basic Auth (File)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/access-control/basic_auth_file_store.sh
  access-control-basic-auth-ldap-store:
    name: HTTP - Basic Auth (LDAP)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/access-control/basic_auth_ldap_store.sh
  access-control-jwt-auth:
    name: HTTP - JWT Auth
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/access-control/jwt_auth.sh
  access-control-oauth-bearer-token:
    name: HTTP - OAuth2 (Bearer Token)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/access-control/oauth2_bearer_token.sh
  access-control-oauth-client-credentials-grant:
    name: HTTP - OAuth2 (Client Credentials Grant)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/access-control/oauth2_client_credentials_grant.sh
  access-control-oauth-password-grant:
    name: HTTP - OAuth2 (Password Grant)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/access-control/oauth2_password_grant.sh
  access-control-oauth-refresh-token-grant:
    name: HTTP - OAuth2 (Refresh Token Grant)
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
      BALLERINA_DOWNLOAD_HOST: ${{ secrets.BALLERINA_DOWNLOAD_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget ${{ env.BALLERINA_DOWNLOAD_HOST }}/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/bbe/access-control/oauth2_refresh_token_grant.sh
