name: Security BBEs

on:
  push:
    paths:
      - 'bbes/**'
      - '.github/workflows/bbes.yml'
  workflow_dispatch:
    inputs:
      artifact_id:
        description: 'GitHub Artifact ID of the Ballerina ZIP produced during Ballerina daily build'
        required: false

jobs:
  general:
    name: General
    runs-on: ubuntu-latest
    env:
      BALLERINA_DEB_URL: ${{ secrets.BALLERINA_DEB_URL }}
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    strategy:
      matrix:
        module: [url, crypto, jwt]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download & Install Ballerina
        run: ./_resources/scripts/install.sh ${{ github.event.inputs.artifact_id }}
      - name: Test
        working-directory: bbes/general
        run: ./${{ matrix.module }}.sh
  http:
    name: HTTP
    runs-on: ubuntu-latest
    env:
      BALLERINA_DEB_URL: ${{ secrets.BALLERINA_DEB_URL }}
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    strategy:
      matrix:
        bbe: [http_ssl_tls, http_mtls, http_basic_auth_file_store, http_basic_auth_ldap_store, http_jwt_auth,
              http_oauth2_bearer_token, http_oauth2_client_credentials_grant, http_oauth2_password_grant,
              http_oauth2_refresh_token_grant, http_oauth2_jwt_bearer_grant]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download & Install Ballerina
        run: ./_resources/scripts/install.sh ${{ github.event.inputs.artifact_id }}
      - name: Test
        working-directory: bbes/http
        run: ./${{ matrix.bbe }}.sh
  graphql:
    name: GraphQL
    runs-on: ubuntu-latest
    env:
      BALLERINA_DEB_URL: ${{ secrets.BALLERINA_DEB_URL }}
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    strategy:
      matrix:
        bbe: [graphql_ssl_tls, graphql_mtls, graphql_basic_auth_file_store, graphql_basic_auth_ldap_store,
              graphql_jwt_auth, graphql_oauth2_bearer_token]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download & Install Ballerina
        run: ./_resources/scripts/install.sh ${{ github.event.inputs.artifact_id }}
      - name: Test
        working-directory: bbes/graphql
        run: ./${{ matrix.bbe }}.sh
  websocket:
    name: WebSocket
    runs-on: ubuntu-latest
    env:
      BALLERINA_DEB_URL: ${{ secrets.BALLERINA_DEB_URL }}
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    strategy:
      matrix:
        bbe: [websocket_ssl_tls, websocket_mtls, websocket_basic_auth_file_store, websocket_basic_auth_ldap_store,
              websocket_jwt_auth, websocket_oauth2_bearer_token, websocket_oauth2_client_credentials_grant,
              websocket_oauth2_password_grant, websocket_oauth2_refresh_token_grant, websocket_oauth2_jwt_bearer_grant]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download & Install Ballerina
        run: ./_resources/scripts/install.sh ${{ github.event.inputs.artifact_id }}
      - name: Test
        working-directory: bbes/websocket
        run: ./${{ matrix.bbe }}.sh
  grpc:
    name: gRPC
    runs-on: ubuntu-latest
    env:
      BALLERINA_DEB_URL: ${{ secrets.BALLERINA_DEB_URL }}
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    strategy:
      matrix:
        bbe: [grpc_ssl_tls, grpc_mtls, grpc_basic_auth_file_store, grpc_basic_auth_ldap_store, grpc_jwt_auth,
              grpc_oauth2_bearer_token, grpc_oauth2_client_credentials_grant, grpc_oauth2_password_grant,
              grpc_oauth2_refresh_token_grant, grpc_oauth2_jwt_bearer_grant]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download & Install Ballerina
        run: ./_resources/scripts/install.sh ${{ github.event.inputs.artifact_id }}
      - name: Test
        working-directory: bbes/grpc
        run: ./${{ matrix.bbe }}.sh
