name: Create Diagram
on:
  workflow_dispatch:
  push:
jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: 'images/codebase.svg'
          excluded_paths: ".github,.gitignore,_config.yml,icons,images,guides,issues"