name: Build

on:
  push:
  workflow_dispatch:

jobs:
  crypto:
    name: Crypto
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: swan-lake-alpha1
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite/packages
        run: |
          ../scripts/crypto/setup.sh
          bal run crypto
  encoding:
    name: Encoding
    runs-on: ubuntu-latest
    env:
        BALLERINA_VERSION: swan-lake-alpha1
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
              java-version: 11
        - name: Download Ballerina
          run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
        - name: Install Ballerina
          run: |
              sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
              sudo apt-get install -f
              bal -v
        - name: Test
          working-directory: test-suite/packages
          run: |
              ../scripts/encoding/setup.sh
              bal run encoding
  auth2:
    name: Basic Auth - LDAP User Store
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: swan-lake-alpha1
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
            sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
            sudo apt-get install -f
            sudo apt-get install jq
            bal -v
      - name: Test
        working-directory: test-suite/packages
        run: |
            ../scripts/auth.basic.ldap/docker.sh
            ../scripts/auth.basic.ldap/ballerina.sh
            ../scripts/auth.basic.ldap/test.sh
  jwt:
    name: JWT Auth
    runs-on: ubuntu-latest
    env:
        BALLERINA_VERSION: swan-lake-alpha1
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
              java-version: 11
        - name: Download Ballerina
          run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
        - name: Install Ballerina
          run: |
              sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
              sudo apt-get install -f
              sudo apt-get install jq
              bal -v
        - name: Test
          working-directory: test-suite/packages
          run: |
              ../scripts/auth.jwt/docker.sh
              ../scripts/auth.jwt/ballerina.sh
              ../scripts/auth.jwt/test.sh
  oauth2:
    name: OAuth2
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: swan-lake-alpha1
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
            sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
            sudo apt-get install -f
            sudo apt-get install jq
            bal -v
      - name: Test
        working-directory: test-suite/packages
        run: |
            ../scripts/auth.jwt/docker.sh
            ../scripts/auth.jwt/ballerina.sh
            ../scripts/auth.jwt/test.sh