name: Test Security Modules

on:
  push:
  workflow_dispatch:

jobs:
  crypto:
    name: Crypto - BBE
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/crypto_test.sh
  encoding:
    name: Encoding - BBE
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/encoding_test.sh
  auth-file:
    name: Basic Auth - File
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          sudo apt-get install jq
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/auth_file_test.sh
  auth-ldap:
    name: Basic Auth - LDAP
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          sudo apt-get install jq
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/auth_ldap_test.sh
  jwt:
    name: JWT Auth
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          sudo apt-get install jq
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/jwt_test.sh
  oauth2:
    name: OAuth2
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget http://dist-dev.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          sudo apt-get install jq
          bal -v
      - name: Test
        working-directory: test-suite
        run: |
          scripts/oauth2_test.sh
